using System;
using System.Collections.Generic;

namespace ProductCrudAPI.Models
{
    public partial class FeeTransferExtract
    {
        public int? MapperId { get; set; }
        public int? DisbursementId { get; set; }
        public string? XmlowningOfficeBuid { get; set; }
        public string? FeeOwningOfficeBuid { get; set; }
        public string? FeeTransferTransType { get; set; }
        public string? FeeTransferStatus { get; set; }
        public string? FileNum { get; set; }
        public string? FileId { get; set; }
        public DateTime? FileOpenDate { get; set; }
        public DateTime? FileSettlementDate { get; set; }
        public string? FileTransactionType { get; set; }
        public string? FileBusinessSegment { get; set; }
        public string? FileServiceTypesConcat { get; set; }
        public string? FirstNewLoanLiabilityAmount { get; set; }
        public string? SalesPriceLiabilityAmount { get; set; }
        public string? FeeType { get; set; }
        public string? FeeCode { get; set; }
        public int? FeeId { get; set; }
        public string? FeeDesc { get; set; }
        public string? FeeGlcode { get; set; }
        public string? FeeDistribution { get; set; }
        public string? FeeSplitAmount { get; set; }
        public string? FeeSalesTax { get; set; }
        public string? RetainedAmount { get; set; }
        public string? FeeOwningOfficeType { get; set; }
        public string? PropertyAddrFirstLine1 { get; set; }
        public string? PropertyAddrSecondLine1 { get; set; }
        public string? PropertyCity1 { get; set; }
        public string? PropertyCounty1 { get; set; }
        public string? PropertyState1 { get; set; }
        public string? PropertyZip1 { get; set; }
        public string? PropertyCountry1 { get; set; }
        public string? PropertyAddrFirstLine2 { get; set; }
        public string? PropertyAddrSecondLine2 { get; set; }
        public string? PropertyCity2 { get; set; }
        public string? PropertyCounty2 { get; set; }
        public string? PropertyState2 { get; set; }
        public string? PropertyZip2 { get; set; }
        public string? PropertyCountry2 { get; set; }
        public string? BusSourceRegionalParentName1 { get; set; }
        public string? BusSourceRegionalParentName2 { get; set; }
        public string? BusSourceRegionalParentCode { get; set; }
        public string? BusSourceRegionalParentId { get; set; }
        public string? BusSourceRegionalParentAddrBookId { get; set; }
        public string? BusSourceRegionalParentEntityType { get; set; }
        public string? BusSourceRegionalParentAddress1 { get; set; }
        public string? BusSourceRegionalParentAddress2 { get; set; }
        public string? BusSourceRegionalParentCity { get; set; }
        public string? BusSourceRegionalParentState { get; set; }
        public string? BusSourceRegionalParentCounty { get; set; }
        public string? BusSourceRegionalParentZip { get; set; }
        public string? BusSourceRegionalParentCountry { get; set; }
        public string? BusSourceName1 { get; set; }
        public string? BusSourceName2 { get; set; }
        public string? BusSourceCode { get; set; }
        public string? BusSourceId { get; set; }
        public string? BusSourceAddrBookId { get; set; }
        public string? BusSourceEntityType { get; set; }
        public string? BusSourceAddress1 { get; set; }
        public string? BusSourceAddress2 { get; set; }
        public string? BusSourceCity { get; set; }
        public string? BusSourceState { get; set; }
        public string? BusSourceCounty { get; set; }
        public string? BusSourceZip { get; set; }
        public string? BusSourceCountry { get; set; }
        public string? BusSourceBusPhone { get; set; }
        public string? BusSourceBusFax { get; set; }
        public string? BusSourceAttention { get; set; }
        public string? BusSourceRefNum { get; set; }
        public string? BusSourceSalesRep1Name { get; set; }
        public string? BusSourceSalesRep1Code { get; set; }
        public string? BusSourceSalesRep1Id { get; set; }
        public string? BusSourceSalesRep1Phone { get; set; }
        public string? BusSourceSalesRep1Fax { get; set; }
        public string? BusSourceSalesRep2Name { get; set; }
        public string? BusSourceSalesRep2Code { get; set; }
        public string? BusSourceSalesRep2Id { get; set; }
        public string? TooregionBuid { get; set; }
        public string? TooregionCode { get; set; }
        public string? TooregionName { get; set; }
        public string? Toobuid { get; set; }
        public string? Toocode { get; set; }
        public string? Tooname { get; set; }
        public string? TooofficialCompanyName { get; set; }
        public string? ToobusAddress1 { get; set; }
        public string? ToobusAddress2 { get; set; }
        public string? ToobusCity { get; set; }
        public string? ToobusCounty { get; set; }
        public string? ToobusState { get; set; }
        public string? ToobusZip { get; set; }
        public string? ToobusCountry { get; set; }
        public string? ToomailAddress1 { get; set; }
        public string? ToomailAddress2 { get; set; }
        public string? ToomailCity { get; set; }
        public string? ToomailCounty { get; set; }
        public string? ToomailState { get; set; }
        public string? ToomailZip { get; set; }
        public string? ToomailCountry { get; set; }
        public string? TootitleAgentType { get; set; }
        public string? TooglclientCode { get; set; }
        public string? ToogldivisionCode { get; set; }
        public string? Toot32companyOfficeNumber { get; set; }
        public string? ToofficerName { get; set; }
        public string? ToofficerCode { get; set; }
        public string? ToohomeOfficeBuid { get; set; }
        public string? ToounderwriterId { get; set; }
        public string? ToounderwriterCode { get; set; }
        public string? ToounderwriterName { get; set; }
        public string? EooregionBuid { get; set; }
        public string? EooregionCode { get; set; }
        public string? EooregionName { get; set; }
        public string? Eoobuid { get; set; }
        public string? Eoocode { get; set; }
        public string? Eooname { get; set; }
        public string? EooofficialCompanyName { get; set; }
        public string? EoobusAddress1 { get; set; }
        public string? EoobusAddress2 { get; set; }
        public string? EoobusCity { get; set; }
        public string? EoobusCounty { get; set; }
        public string? EoobusState { get; set; }
        public string? EoobusZip { get; set; }
        public string? EoobusCountry { get; set; }
        public string? EoomailAddress1 { get; set; }
        public string? EoomailAddress2 { get; set; }
        public string? EoomailCity { get; set; }
        public string? EoomailCounty { get; set; }
        public string? EoomailState { get; set; }
        public string? EoomailZip { get; set; }
        public string? EoomailCountry { get; set; }
        public string? EooglclientCode { get; set; }
        public string? EoogldivisionCode { get; set; }
        public string? Eoot32companyOfficeNumber { get; set; }
        public string? EoofficerName { get; set; }
        public string? EoofficerCode { get; set; }
        public string? EoohomeOfficeBuid { get; set; }
        public string? BuyerNameFirst1 { get; set; }
        public string? BuyerNameMiddle1 { get; set; }
        public string? BuyerNameLast1 { get; set; }
        public string? BuyerNameSuffix1 { get; set; }
        public string? BuyerNameShort1 { get; set; }
        public string? BuyerSpouseNameFirst1 { get; set; }
        public string? BuyerSpouseNameMiddle1 { get; set; }
        public string? BuyerSpouseNameLast1 { get; set; }
        public string? BuyerSpouseNameSuffix1 { get; set; }
        public string? BuyerNameFirst2 { get; set; }
        public string? BuyerNameMiddle2 { get; set; }
        public string? BuyerNameLast2 { get; set; }
        public string? BuyerNameSuffix2 { get; set; }
        public string? BuyerNameShort2 { get; set; }
        public string? BuyerSpouseNameFirst2 { get; set; }
        public string? BuyerSpouseNameMiddle2 { get; set; }
        public string? BuyerSpouseNameLast2 { get; set; }
        public string? BuyerSpouseNameSuffix2 { get; set; }
        public string? BuyerNameFirst3 { get; set; }
        public string? BuyerNameMiddle3 { get; set; }
        public string? BuyerNameLast3 { get; set; }
        public string? BuyerNameSuffix3 { get; set; }
        public string? BuyerNameShort3 { get; set; }
        public string? BuyerSpouseNameFirst3 { get; set; }
        public string? BuyerSpouseNameMiddle3 { get; set; }
        public string? BuyerSpouseNameLast3 { get; set; }
        public string? BuyerSpouseNameSuffix3 { get; set; }
        public string? BuyerNameFirst4 { get; set; }
        public string? BuyerNameMiddle4 { get; set; }
        public string? BuyerNameLast4 { get; set; }
        public string? BuyerNameSuffix4 { get; set; }
        public string? BuyerNameShort4 { get; set; }
        public string? BuyerSpouseNameFirst4 { get; set; }
        public string? BuyerSpouseNameMiddle4 { get; set; }
        public string? BuyerSpouseNameLast4 { get; set; }
        public string? BuyerSpouseNameSuffix4 { get; set; }
        public string? BuyerNameFirst5 { get; set; }
        public string? BuyerNameMiddle5 { get; set; }
        public string? BuyerNameLast5 { get; set; }
        public string? BuyerNameSuffix5 { get; set; }
        public string? BuyerNameShort5 { get; set; }
        public string? BuyerSpouseNameFirst5 { get; set; }
        public string? BuyerSpouseNameMiddle5 { get; set; }
        public string? BuyerSpouseNameLast5 { get; set; }
        public string? BuyerSpouseNameSuffix5 { get; set; }
        public string? BuyerNameFirst6 { get; set; }
        public string? BuyerNameMiddle6 { get; set; }
        public string? BuyerNameLast6 { get; set; }
        public string? BuyerNameSuffix6 { get; set; }
        public string? BuyerNameShort6 { get; set; }
        public string? BuyerSpouseNameFirst6 { get; set; }
        public string? BuyerSpouseNameMiddle6 { get; set; }
        public string? BuyerSpouseNameLast6 { get; set; }
        public string? BuyerSpouseNameSuffix6 { get; set; }
        public string? BuyerNameFirst7 { get; set; }
        public string? BuyerNameMiddle7 { get; set; }
        public string? BuyerNameLast7 { get; set; }
        public string? BuyerNameSuffix7 { get; set; }
        public string? BuyerNameShort7 { get; set; }
        public string? BuyerSpouseNameFirst7 { get; set; }
        public string? BuyerSpouseNameMiddle7 { get; set; }
        public string? BuyerSpouseNameLast7 { get; set; }
        public string? BuyerSpouseNameSuffix7 { get; set; }
        public string? BuyerNameFirst8 { get; set; }
        public string? BuyerNameMiddle8 { get; set; }
        public string? BuyerNameLast8 { get; set; }
        public string? BuyerNameSuffix8 { get; set; }
        public string? BuyerNameShort8 { get; set; }
        public string? BuyerSpouseNameFirst8 { get; set; }
        public string? BuyerSpouseNameMiddle8 { get; set; }
        public string? BuyerSpouseNameLast8 { get; set; }
        public string? BuyerSpouseNameSuffix8 { get; set; }
        public string? BuyerNameFirst9 { get; set; }
        public string? BuyerNameMiddle9 { get; set; }
        public string? BuyerNameLast9 { get; set; }
        public string? BuyerNameSuffix9 { get; set; }
        public string? BuyerNameShort9 { get; set; }
        public string? BuyerSpouseNameFirst9 { get; set; }
        public string? BuyerSpouseNameMiddle9 { get; set; }
        public string? BuyerSpouseNameLast9 { get; set; }
        public string? BuyerSpouseNameSuffix9 { get; set; }
        public string? BuyerNameFirst10 { get; set; }
        public string? BuyerNameMiddle10 { get; set; }
        public string? BuyerNameLast10 { get; set; }
        public string? BuyerNameSuffix10 { get; set; }
        public string? BuyerNameShort10 { get; set; }
        public string? BuyerSpouseNameFirst10 { get; set; }
        public string? BuyerSpouseNameMiddle10 { get; set; }
        public string? BuyerSpouseNameLast10 { get; set; }
        public string? BuyerSpouseNameSuffix10 { get; set; }
        public string? SellerNameFirst1 { get; set; }
        public string? SellerNameMiddle1 { get; set; }
        public string? SellerNameLast1 { get; set; }
        public string? SellerNameSuffix1 { get; set; }
        public string? SellerNameShort1 { get; set; }
        public string? SellerSpouseNameFirst1 { get; set; }
        public string? SellerSpouseNameMiddle1 { get; set; }
        public string? SellerSpouseNameLast1 { get; set; }
        public string? SellerSpouseNameSuffix1 { get; set; }
        public string? SellerNameFirst2 { get; set; }
        public string? SellerNameMiddle2 { get; set; }
        public string? SellerNameLast2 { get; set; }
        public string? SellerNameSuffix2 { get; set; }
        public string? SellerNameShort2 { get; set; }
        public string? SellerSpouseNameFirst2 { get; set; }
        public string? SellerSpouseNameMiddle2 { get; set; }
        public string? SellerSpouseNameLast2 { get; set; }
        public string? SellerSpouseNameSuffix2 { get; set; }
        public string? SellerNameFirst3 { get; set; }
        public string? SellerNameMiddle3 { get; set; }
        public string? SellerNameLast3 { get; set; }
        public string? SellerNameSuffix3 { get; set; }
        public string? SellerNameShort3 { get; set; }
        public string? SellerSpouseNameFirst3 { get; set; }
        public string? SellerSpouseNameMiddle3 { get; set; }
        public string? SellerSpouseNameLast3 { get; set; }
        public string? SellerSpouseNameSuffix3 { get; set; }
        public string? SellerNameFirst4 { get; set; }
        public string? SellerNameMiddle4 { get; set; }
        public string? SellerNameLast4 { get; set; }
        public string? SellerNameSuffix4 { get; set; }
        public string? SellerNameShort4 { get; set; }
        public string? SellerSpouseNameFirst4 { get; set; }
        public string? SellerSpouseNameMiddle4 { get; set; }
        public string? SellerSpouseNameLast4 { get; set; }
        public string? SellerSpouseNameSuffix4 { get; set; }
        public string? SellerNameFirst5 { get; set; }
        public string? SellerNameMiddle5 { get; set; }
        public string? SellerNameLast5 { get; set; }
        public string? SellerNameSuffix5 { get; set; }
        public string? SellerNameShort5 { get; set; }
        public string? SellerSpouseNameFirst5 { get; set; }
        public string? SellerSpouseNameMiddle5 { get; set; }
        public string? SellerSpouseNameLast5 { get; set; }
        public string? SellerSpouseNameSuffix5 { get; set; }
        public string? SellerNameFirst6 { get; set; }
        public string? SellerNameMiddle6 { get; set; }
        public string? SellerNameLast6 { get; set; }
        public string? SellerNameSuffix6 { get; set; }
        public string? SellerNameShort6 { get; set; }
        public string? SellerSpouseNameFirst6 { get; set; }
        public string? SellerSpouseNameMiddle6 { get; set; }
        public string? SellerSpouseNameLast6 { get; set; }
        public string? SellerSpouseNameSuffix6 { get; set; }
        public string? SellerNameFirst7 { get; set; }
        public string? SellerNameMiddle7 { get; set; }
        public string? SellerNameLast7 { get; set; }
        public string? SellerNameSuffix7 { get; set; }
        public string? SellerNameShort7 { get; set; }
        public string? SellerSpouseNameFirst7 { get; set; }
        public string? SellerSpouseNameMiddle7 { get; set; }
        public string? SellerSpouseNameLast7 { get; set; }
        public string? SellerSpouseNameSuffix7 { get; set; }
        public string? SellerNameFirst8 { get; set; }
        public string? SellerNameMiddle8 { get; set; }
        public string? SellerNameLast8 { get; set; }
        public string? SellerNameSuffix8 { get; set; }
        public string? SellerNameShort8 { get; set; }
        public string? SellerSpouseNameFirst8 { get; set; }
        public string? SellerSpouseNameMiddle8 { get; set; }
        public string? SellerSpouseNameLast8 { get; set; }
        public string? SellerSpouseNameSuffix8 { get; set; }
        public string? SellerNameFirst9 { get; set; }
        public string? SellerNameMiddle9 { get; set; }
        public string? SellerNameLast9 { get; set; }
        public string? SellerNameSuffix9 { get; set; }
        public string? SellerNameShort9 { get; set; }
        public string? SellerSpouseNameFirst9 { get; set; }
        public string? SellerSpouseNameMiddle9 { get; set; }
        public string? SellerSpouseNameLast9 { get; set; }
        public string? SellerSpouseNameSuffix9 { get; set; }
        public string? SellerNameFirst10 { get; set; }
        public string? SellerNameMiddle10 { get; set; }
        public string? SellerNameLast10 { get; set; }
        public string? SellerNameSuffix10 { get; set; }
        public string? SellerNameShort10 { get; set; }
        public string? SellerSpouseNameFirst10 { get; set; }
        public string? SellerSpouseNameMiddle10 { get; set; }
        public string? SellerSpouseNameLast10 { get; set; }
        public string? SellerSpouseNameSuffix10 { get; set; }
        public string? DocumentNum { get; set; }
        public DateTime? IssueDate { get; set; }
        public DateTime? PostedOnDate { get; set; }
        public DateTime? T32extractDate { get; set; }
        public DateTime? GlextractDate { get; set; }
        public string? FeeTransferTotalAmount { get; set; }
        public string? FeeTransferComments { get; set; }
        public string? BankAccountNum { get; set; }
        public string? BankCode { get; set; }
        public string? BankId { get; set; }
        public string? SmsbankCode { get; set; }
        public string? BankName { get; set; }
        public string? BankAddress1 { get; set; }
        public string? BankAddress2 { get; set; }
        public string? BankCity { get; set; }
        public string? BankCounty { get; set; }
        public string? BankState { get; set; }
        public string? BankZip { get; set; }
        public string? BankCountry { get; set; }
        public string? AdhocBusinessSourceFlg { get; set; }
        public string? SubjectToSalesTaxFlg { get; set; }
        public string? CompanyIncomeFeeFlg { get; set; }
        public string? OfficeIncomeFeeFlg { get; set; }
        public string? TitleOfficerFeeFlg { get; set; }
        public string? EscrowOfficerFeeFlg { get; set; }
        public string? SalesRepFeeFlg { get; set; }
        public string? SubjectToRemittanceFlg { get; set; }
        public string? SubjectToPromulgatedRateFlg { get; set; }
        public string? GovernmentReportableFlg { get; set; }
        public string? RateTypeFlg { get; set; }
        public string? TransactionCodeFlg { get; set; }
        public string? InvoiceNum { get; set; }
        public DateTime? InvoiceExportDate { get; set; }
        public string? InvoiceStatus { get; set; }
        public DateTime? AdjDate { get; set; }
        public string? AdjReason { get; set; }
        public string? AdjDescription { get; set; }
        public int? ServiceFileFeeId { get; set; }
        public string? ToofastStatCd { get; set; }
        public string? EoofastStatCd { get; set; }
        public int FeeTransferExtractsId { get; set; }
    }
}
