using System;
using System.Collections.Generic;

namespace ProductCrudAPI.Models
{
    public partial class InvoiceExtractFee
    {
        public int? InvHistId { get; set; }
        public int? InvId { get; set; }
        public string? InvNum { get; set; }
        public string? InvExportReqDate { get; set; }
        public string? InvComments { get; set; }
        public string? InvFormat { get; set; }
        public string? InvStatus { get; set; }
        public string? FeeAction { get; set; }
        public int? ServFileFeeId { get; set; }
        public string? FeeCode { get; set; }
        public string? FeeDescr { get; set; }
        public string? FeeType { get; set; }
        public short? FeeInvSeqNum { get; set; }
        public string? FeeGlcode { get; set; }
        public string? FeeSetupGlcode { get; set; }
        public short? FeeSubjectToSalesTaxFlag { get; set; }
        public string? FeeBuyerCharge { get; set; }
        public string? FeeSellerCharge { get; set; }
        public string? FeeBuyerTax { get; set; }
        public string? FeeSellerTax { get; set; }
        public string? Ftnum { get; set; }
        public string? FtissueDt { get; set; }
        public string? FtadjustDt { get; set; }
        public string? FtadjustType { get; set; }
        public string? InvToParentAddrBookEntryId { get; set; }
        public int? InvToAddrBookEntryId { get; set; }
        public string? InvToCode { get; set; }
        public int? InvToAdHocFlag { get; set; }
        public string? InvToName1 { get; set; }
        public string? InvToName2 { get; set; }
        public string? InvToContact { get; set; }
        public string? InvToRefNum { get; set; }
        public string? InvToPhoneNum { get; set; }
        public string? InvToBillAddrStreet1 { get; set; }
        public string? InvToBillAddrStreet2 { get; set; }
        public string? InvToBillAddrCity { get; set; }
        public string? InvToBillAddrState { get; set; }
        public string? InvToBillAddrZip { get; set; }
        public string? InvToBillAddrCountry { get; set; }
        public string? InvToBusAddrStreet1 { get; set; }
        public string? InvToBusAddrStreet2 { get; set; }
        public string? InvToBusAddrCity { get; set; }
        public string? InvToBusAddrState { get; set; }
        public string? InvToBusAddrZip { get; set; }
        public string? InvToBusAddrCountry { get; set; }
        public string? BillToName1 { get; set; }
        public string? BillToName2 { get; set; }
        public string? BillToPerson { get; set; }
        public int? FileId { get; set; }
        public string? FileNum { get; set; }
        public string? FileOpenDate { get; set; }
        public string? FileOrderType { get; set; }
        public string? FileTransType { get; set; }
        public string? FileBusSeg { get; set; }
        public string? Tooid { get; set; }
        public string? Toocode { get; set; }
        public string? Tooname { get; set; }
        public string? TooglclientCode { get; set; }
        public string? ToogldivisionCode { get; set; }
        public string? TooofficialName1 { get; set; }
        public string? TooofficialName2 { get; set; }
        public string? TooremitAddrStreet1 { get; set; }
        public string? TooremitAddrStreet2 { get; set; }
        public string? TooremitAddrStreet3 { get; set; }
        public string? TooremitAddrStreet4 { get; set; }
        public string? TooremitAddrCity { get; set; }
        public string? TooremitAddrState { get; set; }
        public string? TooremitAddrZip { get; set; }
        public string? TooremitAddrCountry { get; set; }
        public string? ToomailAddrStreet1 { get; set; }
        public string? ToomailAddrStreet2 { get; set; }
        public string? ToomailAddrCity { get; set; }
        public string? ToomailAddrState { get; set; }
        public string? ToomailAddrZip { get; set; }
        public string? ToomailAddrCountry { get; set; }
        public string? ToobillAddrStreet1 { get; set; }
        public string? ToobillAddrStreet2 { get; set; }
        public string? ToobillAddrCity { get; set; }
        public string? ToobillAddrState { get; set; }
        public string? ToobillAddrZip { get; set; }
        public string? ToobillAddrCountry { get; set; }
        public string? ToophoneNum { get; set; }
        public string? Eooid { get; set; }
        public string? Eoocode { get; set; }
        public string? Eooname { get; set; }
        public string? EooglclientCode { get; set; }
        public string? EoogldivisionCode { get; set; }
        public string? EooofficialName1 { get; set; }
        public string? EooofficialName2 { get; set; }
        public string? EooremitAddrStreet1 { get; set; }
        public string? EooremitAddrStreet2 { get; set; }
        public string? EooremitAddrStreet3 { get; set; }
        public string? EooremitAddrStreet4 { get; set; }
        public string? EooremitAddrCity { get; set; }
        public string? EooremitAddrState { get; set; }
        public string? EooremitAddrZip { get; set; }
        public string? EooremitAddrCountry { get; set; }
        public string? EoomailAddrStreet1 { get; set; }
        public string? EoomailAddrStreet2 { get; set; }
        public string? EoomailAddrCity { get; set; }
        public string? EoomailAddrState { get; set; }
        public string? EoomailAddrZip { get; set; }
        public string? EoomailAddrCountry { get; set; }
        public string? EoobillAddrStreet1 { get; set; }
        public string? EoobillAddrStreet2 { get; set; }
        public string? EoobillAddrCity { get; set; }
        public string? EoobillAddrState { get; set; }
        public string? EoobillAddrZip { get; set; }
        public string? EoobillAddrCountry { get; set; }
        public string? EoophoneNum { get; set; }
        public string? RegionCode { get; set; }
        public string? RegionName { get; set; }
        public string? Tocode { get; set; }
        public string? Toname { get; set; }
        public string? TohomeOfficeCode { get; set; }
        public string? Sr1code { get; set; }
        public string? Sr1name { get; set; }
        public string? Sr1homeOfficeCode { get; set; }
        public string? Eocode { get; set; }
        public string? Eoname { get; set; }
        public string? EohomeOfficeCode { get; set; }
        public string? Sr2code { get; set; }
        public string? Sr2name { get; set; }
        public string? Sr2homeOfficeCode { get; set; }
        public string? P1a1street1 { get; set; }
        public string? P1a1street2 { get; set; }
        public string? P1a1city { get; set; }
        public string? P1a1county { get; set; }
        public string? P1a1state { get; set; }
        public string? P1a1zip { get; set; }
        public string? P1a1country { get; set; }
        public string? P1a2street1 { get; set; }
        public string? P1a2street2 { get; set; }
        public string? P1a2city { get; set; }
        public string? P1a2county { get; set; }
        public string? P1a2state { get; set; }
        public string? P1a2zip { get; set; }
        public string? P1a2country { get; set; }
        public string? P1annApn1 { get; set; }
        public string? P1annApn2 { get; set; }
        public string? P1annApn3 { get; set; }
        public string? P1suppApn1 { get; set; }
        public string? P1suppApn2 { get; set; }
        public string? P1suppApn3 { get; set; }
        public string? P1suppApn4 { get; set; }
        public string? P1suppApn5 { get; set; }
        public string? P2a1street1 { get; set; }
        public string? P2a1street2 { get; set; }
        public string? P2a1city { get; set; }
        public string? P2a1county { get; set; }
        public string? P2a1state { get; set; }
        public string? P2a1zip { get; set; }
        public string? P2a1country { get; set; }
        public string? P2a2street1 { get; set; }
        public string? P2a2street2 { get; set; }
        public string? P2a2city { get; set; }
        public string? P2a2county { get; set; }
        public string? P2a2state { get; set; }
        public string? P2a2zip { get; set; }
        public string? P2a2country { get; set; }
        public string? P2annApn1 { get; set; }
        public string? P2annApn2 { get; set; }
        public string? P2annApn3 { get; set; }
        public string? P2suppApn1 { get; set; }
        public string? P2suppApn2 { get; set; }
        public string? P2suppApn3 { get; set; }
        public string? P2suppApn4 { get; set; }
        public string? P2suppApn5 { get; set; }
        public string? Seller1 { get; set; }
        public string? Seller2 { get; set; }
        public string? Seller3 { get; set; }
        public string? Seller4 { get; set; }
        public string? Seller5 { get; set; }
        public string? Seller6 { get; set; }
        public string? Seller7 { get; set; }
        public string? Seller8 { get; set; }
        public string? Seller9 { get; set; }
        public string? Seller10 { get; set; }
        public string? Buyer1 { get; set; }
        public string? Buyer2 { get; set; }
        public string? Buyer3 { get; set; }
        public string? Buyer4 { get; set; }
        public string? Buyer5 { get; set; }
        public string? Buyer6 { get; set; }
        public string? Buyer7 { get; set; }
        public string? Buyer8 { get; set; }
        public string? Buyer9 { get; set; }
        public string? Buyer10 { get; set; }
        public string? FileNewLoan1RecordingDate { get; set; }
        public string? FileNewLoan1LiabilityAmt { get; set; }
        public string? FileSalesPriceLiabilityAmt { get; set; }
    }
}
