using System;
using System.Collections.Generic;

namespace ProductCrudAPI.Models
{
    public partial class RoadHomeLog
    {
        public int RoadHomeLogId { get; set; }
        public string? FastId { get; set; }
        public string? ErrorMsg { get; set; }
        public DateTime BatchTime { get; set; }
        public short ProcessedFlag { get; set; }
        public short SuccessFlag { get; set; }
        public string EGrantsAppid { get; set; } = null!;
        public string? SubmittedToFirstAmDate { get; set; }
        public string? SubmittedToFirstAmBatch { get; set; }
        public string? ApplicantNameLast { get; set; }
        public string? ApplicantNameFirst { get; set; }
        public string? ApplicantNameMiddle { get; set; }
        public string? ApplicantNameSuffix { get; set; }
        public string? ApplicantSsn { get; set; }
        public string? ApplicantDob { get; set; }
        public string? ApplicantMaritalStatus { get; set; }
        public string? ApplicantMailingStreet1 { get; set; }
        public string? ApplicantMailingStreet2 { get; set; }
        public string? ApplicantMailingCity { get; set; }
        public string? ApplicantMailingState { get; set; }
        public string? ApplicantMailingZip { get; set; }
        public string? ApplicantPhoneHome { get; set; }
        public string? ApplicantPhoneWork { get; set; }
        public string? ApplicantPhoneCell { get; set; }
        public string? ApplicantFax { get; set; }
        public string? ApplicantEmail { get; set; }
        public string? CoApplicantNameLast { get; set; }
        public string? CoApplicantNameFirst { get; set; }
        public string? CoApplicantNameMiddle { get; set; }
        public string? CoApplicantNameSuffix { get; set; }
        public string? CoApplicantSsn { get; set; }
        public string? CoApplicantDob { get; set; }
        public string? CoApplicantMaritalStatus { get; set; }
        public string? CoApplicantMailingStreet1 { get; set; }
        public string? CoApplicantMailingStreet2 { get; set; }
        public string? CoApplicantMailingCity { get; set; }
        public string? CoApplicantMailingState { get; set; }
        public string? CoApplicantMailingZip { get; set; }
        public string? CoApplicantPhoneHome { get; set; }
        public string? CoApplicantPhoneWork { get; set; }
        public string? CoApplicantPhoneCell { get; set; }
        public string? CoApplicantFax { get; set; }
        public string? CoApplicantEmail { get; set; }
        public string? PropertyStreet1 { get; set; }
        public string? PropertyStreet2 { get; set; }
        public string? PropertyCity { get; set; }
        public string? PropertyParish { get; set; }
        public string? PropertyState { get; set; }
        public string? PropertyZip { get; set; }
        public string? PropertyTaxParcelId { get; set; }
        public string? PropertyType { get; set; }
        public string? PropertyMobileHome { get; set; }
        public string? PropertyFemaId1 { get; set; }
        public string? PropertyFemaId2 { get; set; }
        public string? Owner1NameLast { get; set; }
        public string? Owner1NameFirst { get; set; }
        public string? Owner1NameMiddle { get; set; }
        public string? Owner1NameSuffix { get; set; }
        public string? Owner1Ssn { get; set; }
        public string? Owner1Dob { get; set; }
        public string? Owner1MailingStreet1 { get; set; }
        public string? Owner1MailingStreet2 { get; set; }
        public string? Owner1MailingCity { get; set; }
        public string? Owner1MailingState { get; set; }
        public string? Owner1MailingZip { get; set; }
        public string? Owner1PhoneHome { get; set; }
        public string? Owner1PhoneWork { get; set; }
        public string? Owner1Fax { get; set; }
        public string? Owner1Email { get; set; }
        public string? Owner2NameLast { get; set; }
        public string? Owner2NameFirst { get; set; }
        public string? Owner2NameMiddle { get; set; }
        public string? Owner2NameSuffix { get; set; }
        public string? Owner2Ssn { get; set; }
        public string? Owner2Dob { get; set; }
        public string? Owner2MailingStreet1 { get; set; }
        public string? Owner2MailingStreet2 { get; set; }
        public string? Owner2MailingCity { get; set; }
        public string? Owner2MailingState { get; set; }
        public string? Owner2MailingZip { get; set; }
        public string? Owner2PhoneHome { get; set; }
        public string? Owner2PhoneWork { get; set; }
        public string? Owner2Fax { get; set; }
        public string? Owner2Email { get; set; }
        public string? Owner3NameLast { get; set; }
        public string? Owner3NameFirst { get; set; }
        public string? Owner3NameMiddle { get; set; }
        public string? Owner3NameSuffix { get; set; }
        public string? Owner3Ssn { get; set; }
        public string? Owner3Dob { get; set; }
        public string? Owner3MailingStreet1 { get; set; }
        public string? Owner3MailingStreet2 { get; set; }
        public string? Owner3MailingCity { get; set; }
        public string? Owner3MailingState { get; set; }
        public string? Owner3MailingZip { get; set; }
        public string? Owner3PhoneHome { get; set; }
        public string? Owner3PhoneWork { get; set; }
        public string? Owner3Fax { get; set; }
        public string? Owner3Email { get; set; }
        public string? Owner4NameLast { get; set; }
        public string? Owner4NameFirst { get; set; }
        public string? Owner4NameMiddle { get; set; }
        public string? Owner4NameSuffix { get; set; }
        public string? Owner4Ssn { get; set; }
        public string? Owner4Dob { get; set; }
        public string? Owner4MailingStreet1 { get; set; }
        public string? Owner4MailingStreet2 { get; set; }
        public string? Owner4MailingCity { get; set; }
        public string? Owner4MailingState { get; set; }
        public string? Owner4MailingZip { get; set; }
        public string? Owner4PhoneHome { get; set; }
        public string? Owner4PhoneWork { get; set; }
        public string? Owner4Fax { get; set; }
        public string? Owner4Email { get; set; }
        public string? Owner5NameLast { get; set; }
        public string? Owner5NameFirst { get; set; }
        public string? Owner5NameMiddle { get; set; }
        public string? Owner5NameSuffix { get; set; }
        public string? Owner5Ssn { get; set; }
        public string? Owner5Dob { get; set; }
        public string? Owner5MailingStreet1 { get; set; }
        public string? Owner5MailingStreet2 { get; set; }
        public string? Owner5MailingCity { get; set; }
        public string? Owner5MailingState { get; set; }
        public string? Owner5MailingZip { get; set; }
        public string? Owner5PhoneHome { get; set; }
        public string? Owner5PhoneWork { get; set; }
        public string? Owner5Fax { get; set; }
        public string? Owner5Email { get; set; }
        public string? Owner6NameLast { get; set; }
        public string? Owner6NameFirst { get; set; }
        public string? Owner6NameMiddle { get; set; }
        public string? Owner6NameSuffix { get; set; }
        public string? Owner6Ssn { get; set; }
        public string? Owner6Dob { get; set; }
        public string? Owner6MailingStreet1 { get; set; }
        public string? Owner6MailingStreet2 { get; set; }
        public string? Owner6MailingCity { get; set; }
        public string? Owner6MailingState { get; set; }
        public string? Owner6MailingZip { get; set; }
        public string? Owner6PhoneHome { get; set; }
        public string? Owner6PhoneWork { get; set; }
        public string? Owner6Fax { get; set; }
        public string? Owner6Email { get; set; }
        public string? FirstMortgageeName { get; set; }
        public string? FirstMortgageeLoanNo { get; set; }
        public string? FirstMortgageeLoanBal { get; set; }
        public string? SecondMortgageeName { get; set; }
        public string? SecondMortgageeLoanNo { get; set; }
        public string? SecondMortgageeLoanBal { get; set; }
        public string? ThirdMortgageeName { get; set; }
        public string? ThirdMortgageeLoanNo { get; set; }
        public string? ThirdMortgageeLoanBal { get; set; }
        public string? FourthMortgageeName { get; set; }
        public string? FourthMortgageeLoanNo { get; set; }
        public string? FourthMortgageeLoanBal { get; set; }
        public string? TaxLiens { get; set; }
        public string? SbaName { get; set; }
        public string? SbaAppNo { get; set; }
        public string? SbaLoanNo { get; set; }
    }
}
